site_name: Data Science Baseline Project Template
site_description: A project template and directory structure for Python data science projects.
repo_url: https://github.com/mraarone/dsbaseline
edit_uri: edit/master/docs/docs
copyright: MIT Copyright.
theme: cinder
extra_css:
  - css/extra.css
nav:
  - Home: index.md
